### ISSUE TITLE
Corporate SSL, Test Kitchen and compile-time running

### ISSUE THREAD

**Issue by isuftin** [sethvargo/chef-sugar#145]
I have a wrapper cookbook for https://github.com/johnbellone/consul-cookbook

That cookbook includes Chef Sugar as the first order of business: 
https://github.com/johnbellone/consul-cookbook/blob/v2.2.0/recipes/default.rb#L7

I run Test Kitchen (and my EC2 instances) behind a corporate SSL intercept scheme. 

When firing up Test Kitchen, I get the following error:

```
...
       Installing Cookbook Gems:
       Compiling Cookbooks...
       [2016-11-03T20:22:04+00:00] WARN: Chef::Provider::YumRepository already exists!  Cannot create deprecation class for LWRP provider yum_repository from cookbook yum
       [2016-11-03T20:22:04+00:00] WARN: YumRepository already exists!  Deprecation class overwrites Custom resource yum_repository from cookbook yum
       Recipe: chef-sugar::default
         * chef_gem[chef-sugar] action install[2016-11-03T20:22:05+00:00] WARN:  failed to find gem chef-sugar (= 3.4.0) from [https://rubygems.org/]


           ================================================================================
           Error executing action `install` on resource 'chef_gem[chef-sugar]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '2'
           ---- Begin output of /opt/chef/embedded/bin/gem install chef-sugar -q --no-rdoc --no-ri -v "3.4.0" ----
           STDOUT:
           STDERR: ERROR:  Could not find a valid gem 'chef-sugar' (= 3.4.0), here is why:
              Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)
           ---- End output of /opt/chef/embedded/bin/gem install chef-sugar -q --no-rdoc --no-ri -v "3.4.0" ----
           Ran /opt/chef/embedded/bin/gem install chef-sugar -q --no-rdoc --no-ri -v "3.4.0" returned 2

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/chef-sugar/recipes/default.rb:23:in `from_file'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:347:in `load_recipe'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:303:in `block in include_recipe'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `each'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `include_recipe'
           /tmp/kitchen/cache/cookbooks/consul/recipes/default.rb:7:in `from_file'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:347:in `load_recipe'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:303:in `block in include_recipe'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `each'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `include_recipe'
           /tmp/kitchen/cache/cookbooks/owi-consul/recipes/server.rb:25:in `from_file'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:347:in `load_recipe'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/chef-sugar/recipes/default.rb

            23:   chef_gem 'chef-sugar' do
            24:     version gem_version
            25:     compile_time true
            26:   end
            27: else

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/chef-sugar/recipes/default.rb:23:in `from_file'

           chef_gem("chef-sugar") do
             package_name "chef-sugar"
             action [:install]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :chef_gem
             cookbook_name "chef-sugar"
             recipe_name "default"
             version "3.4.0"
             compile_time true
             gem_binary "/opt/chef/embedded/bin/gem"
           end

           Platform:
           ---------
           x86_64-linux

...
```

This is run on Bento CentOS 6.7 VM. 

One of the first cookbooks in my runlist in Test Kitchen installs the corporate SSL root cert onto the VM which clears this problem but because the Gem tries to install at compile time, I never get a chance to run that first cookbook and the run fails. 

I tried adding to the Kitchen YML:
```
provisioner:
  name: chef_zero
  client_rb: 
    chef_gem_compile_time: false
```

..to no avail

I wonder if there are any techniques or fixes that I can try to have this gem install during the run of the cookbook that calls it?

**Comment by johnbellone** [comment]
@isuftin We're using the [vagrant-ca-certificate plugin](https://github.com/williambailey/vagrant-ca-certificates) to manage the certificates. We set a [global Vagrantfile](https://www.vagrantup.com/docs/vagrantfile/) that looks like:
```ruby
Vagrant.configure('2') do |config|
  config.omnibus.chef_version = :latest
  config.berkshelf.enabled = true
  config.cache.scope = :box
  config.cache.auto_detect = true
  config.proxy.enabled = true
end
```

FWIW, we also use [vagrant-proxyconf](https://github.com/tmatilai/vagrant-proxyconf) and a global Kitchen configuration that sets the http[s] and no_proxy environment variables.
