### ISSUE TITLE
Is it possible to use chef-sugar in Policyfile.rb definitions?

### ISSUE THREAD

**Issue by Tzrlk** [sethvargo/chef-sugar#149]
The attribute definition DSL provided by `Chef::Sugar::Node` is excellent, and I'd really like to use it, but every time I try and `require 'chef-sugar'` in my `Policyfile.rb`, it just says:

    >chef install --debug

    Error: Failed to generate Policyfile.lock
    Reason: (ChefDK::PolicyfileError) Evaluation of policyfile 'C:/code/chef/nginx/Policyfile.rb' raised an exception
    Exception: LoadError "cannot load such file -- chef-sugar"

    Relevant Code:
        5: require 'chef-sugar'

    Backtrace:
        C:/code/chef/bravura_nginx/Policyfile.rb:7:in `eval_policyfile'

    C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-dk-1.1.16/lib/chef-dk/policyfile_compiler.rb:72:in `error!'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-dk-1.1.16/lib/chef-dk/policyfile_services/install.rb:89:in `generate_lock_and_install'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-dk-1.1.16/lib/chef-dk/policyfile_services/install.rb:60:in `run'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-dk-1.1.16/lib/chef-dk/command/install.rb:78:in `run'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-dk-1.1.16/lib/chef-dk/command/base.rb:58:in `run_with_default_options'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-dk-1.1.16/lib/chef-dk/cli.rb:73:in `run'
    C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-dk-1.1.16/bin/chef:25:in `<top (required)>'
    C:/opscode/chefdk/bin/chef:93:in `load'
    C:/opscode/chefdk/bin/chef:93:in `<main>'

Any idea on how to get this monkeypatched in? I'd do it myself, but my Ruby isn't that advanced yet.

**Comment by johnbellone** [comment]
I don't know why you would want to do this. A policyfile is compiled on a build machine (or a developer workstation) and produces a machine-readable JSON manifest file. It is not executed at run-time of the Chef Client.

**Comment by Tzrlk** [comment]
@johnbellone The idea is to then use chef-sugar to define the attributes in a nested manner, making the authoring and maintenance of the Policyfile easier. The Policyfile is really just any other ruby file, and should be able to support library inclusions.
