### ISSUE TITLE
chef-sugar breaks on Chef 12

### ISSUE THREAD

**Issue by arnaud036** [sethvargo/chef-sugar#89]
Chef sugar method `compile_time` is overriding the Chef 12 new `compile_time` resource and causing the Chef runs to fail with the error below:

```
00:08:04.735 10.69.11.204 [0m  ArgumentError[0m
00:08:04.736 10.69.11.204   -------------[0m
00:08:04.736 10.69.11.204   wrong number of arguments (1 for 0)[0m
00:08:04.736 10.69.11.204   
00:08:04.736 10.69.11.204 [0m  Cookbook Trace:[0m
00:08:04.737 10.69.11.204   ---------------[0m
00:08:04.737 10.69.11.204     /var/chef/cache/cookbooks/aws/recipes/default.rb:22:in `block in from_file'
00:08:04.737 10.69.11.204 [0m    /var/chef/cache/cookbooks/aws/recipes/default.rb:20:in `from_file'
00:08:04.737 10.69.11.204 [0m    /var/chef/cache/cookbooks/rally-fuzzle/recipes/sftp_aws_ebs.rb:11:in `from_file'
00:08:04.737 10.69.11.204 [0m    /var/chef/cache/cookbooks/rally-fuzzle/recipes/sftp.rb:10:in `from_file'[0m
00:08:04.738 10.69.11.204   
00:08:04.738 10.69.11.204 [0m  Relevant File Content:[0m
00:08:04.738 10.69.11.204   ----------------------[0m
00:08:04.738 10.69.11.204   /var/chef/cache/cookbooks/aws/recipes/default.rb:
00:08:04.739 10.69.11.204 [0m  
00:08:04.739 10.69.11.204 [0m   15:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
00:08:04.739 10.69.11.204 [0m   16:  # See the License for the specific language governing permissions and
00:08:04.739 10.69.11.204 [0m   17:  # limitations under the License.
00:08:04.739 10.69.11.204 [0m   18:  #
00:08:04.739 10.69.11.204 [0m   19:  
00:08:04.740 10.69.11.204 [0m   20:  chef_gem 'aws-sdk' do
00:08:04.740 10.69.11.204 [0m   21:    version node['aws']['aws_sdk_version']
00:08:04.740 10.69.11.204 [0m   22>>   compile_time true if respond_to?(:compile_time)
00:08:04.740 10.69.11.204 [0m   23:    action :install
00:08:04.740 10.69.11.204 [0m   24:  end
00:08:04.741 10.69.11.204 [0m   25:  
00:08:04.741 10.69.11.204 [0m   26:  require 'aws-sdk'
```

Please see https://github.com/opscode-cookbooks/xml/issues/22

@sethvargo

**Comment by sethvargo** [comment]
You should check if the resource responds to `:compile_time`, not the recipe...

```ruby
chef_gem 'aws_sdk' do
  compile_time true if Chef::Resource::ChefGem.method_defined?(:compile_time)
end
```

Otherwise you are just opening yourself up to a world of hurt... This is no different than if you defined a custom helper named `compile_time`. This is not an issue with the Chef Sugar cookbook, but rather an issue with how you are checking if the resource responds to a particular method.

**Comment by jtimberman** [comment]
On Chef 11, when using `chef-sugar`, This will return true:

```ruby
Chef::Resource::ChefGem.method_defined?(:compile_time)
```

Because `:compile_time` is a public instance method of `Chef::Sugar::DSL`, which is [included in Chef::Resource](https://github.com/sethvargo/chef-sugar/blob/410a4d6ef7c53d9749395121c435a849fdb85421/lib/chef/sugar.rb#L43) (which means that method is now defined on every resource.

It's not clear to me how to go about it, but I think that the filters aren't meant to be part of `Chef::Resource`? If it weren't included there, then we wouldn't get this issue on Chef 11. Unfortunately we can't just tell people "oh you're using chef-sugar, and Chef 11, upgrade to Chef 12" since we obviously can't know the world of code out there using chef-sugar.

**Comment by jtimberman** [comment]
Okay, to follow up from earlier:

In my test system, this does not work:

```ruby
chef_gem 'chef-vault' do
  version node['chef-vault']['version']
  compile_time true   if Chef::Resource::ChefGem.method_defined?(:compile_time)
end
```

If we use `#instance_methods` with `false` as a parameter, and then see if it has `:compile_time`, then we get the desired behavior.

```ruby
chef_gem 'chef-vault' do
  version node['chef-vault']['version']
  compile_time true if Chef::Resource::ChefGem.instance_methods(false).
                                               include?(:compile_time)
  end
end
```

Hat tip to @scalp42 in [this pull request for the aws cookbook](https://github.com/opscode-cookbooks/aws/pull/110)

It works on Chef 12.1:

```
Starting Chef Client, version 12.1.1
[2015-03-20T03:06:19+00:00] WARN: Child with name 'dna.json' found in multiple directories: /tmp/kitchen/dna.json and /tmp/kitchen/dna.json
resolving cookbooks for run list: ["chef-sugar", "chef-vault"]
Synchronizing Cookbooks:
  - chef-sugar
  - chef-vault
Compiling Cookbooks...
[2015-03-20T03:06:19+00:00] WARN: chef_gem[chef-sugar] chef_gem compile_time installation is deprecated
[2015-03-20T03:06:19+00:00] WARN: chef_gem[chef-sugar] Please set `compile_time false` on the resource to use the new behavior.
[2015-03-20T03:06:19+00:00] WARN: chef_gem[chef-sugar] or set `compile_time true` on the resource if compile_time behavior is required.
Recipe: chef-sugar::default
  * chef_gem[chef-sugar] action nothing (skipped due to action :nothing)
  * chef_gem[chef-sugar] action install (up to date)
Recipe: chef-vault::default
  * chef_gem[chef-vault] action install (up to date)
  Converging 2 resources
Recipe: chef-sugar::default
  * chef_gem[chef-sugar] action nothing (skipped due to action :nothing)
Recipe: chef-vault::default
  * chef_gem[chef-vault] action install (up to date)

Running handlers:
Running handlers complete
Chef Client finished, 0/3 resources updated in 2.028156259 seconds
```

And it works on Chef 11:

```
Starting Chef Client, version 11.16.4
resolving cookbooks for run list: ["chef-sugar", "chef-vault"]
Synchronizing Cookbooks:
  - chef-sugar
  - chef-vault
Compiling Cookbooks...
Recipe: chef-sugar::default
  * chef_gem[chef-sugar] action nothing (skipped due to action :nothing)
  * chef_gem[chef-sugar] action install (up to date)
Recipe: chef-vault::default
  * chef_gem[chef-vault] action install (up to date)
  Converging 2 resources
Recipe: chef-sugar::default
  * chef_gem[chef-sugar] action nothing (skipped due to action :nothing)
Recipe: chef-vault::default
  * chef_gem[chef-vault] action install (up to date)

Running handlers:
Running handlers complete
Chef Client finished, 0/3 resources updated in 1.710153161 seconds
```

Perhaps if `chef-sugar` provided a helper method that made that conditional nicer for this use case? Since `chef-sugar` itself has a recipe that manages `chef_gem[chef-sugar]`, it makes a great candidate for testing such a method. Thoughts?

**Comment by sethvargo** [comment]
I have renamed `compile_time` to `at_compile_time` in v3.0.1.

**Comment by jtimberman** [comment]
❤️❤️❤️

**Comment by nathenharvey** [comment]
We will be hosting a public post mortem on [Wednesday, March 25 at 17:00 UTC / 13:00 EDT / 10:00 PDT](http://www.timeanddate.com/worldclock/fixedtime.html?msg=chef_gem+and+chef_sugar+release+post+mortem&iso=20150325T13&p1=1928&am=50).

During this meeting we will explore ways to improve our collaboration and identify changes like this earlier in the process.

More information is available in [Chef Issue 3107](https://github.com/chef/chef/issues/3107#issuecomment-85337032).
